Django Movie_web/movie/home/urls.py
from django.contrib import admin
from django.urls import path
from home import views

urlpatterns = [

    path('', views.index,name = "index"),
    path("signup/", views.signup, name="signup"),
    path("signin/", views.signin, name="signin"),
    path("logout/", views.logout, name="logout"),

]

Django Movie_web/movie/movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
]
urlpatterns += static(settings.MEDIA_URL ,document_root = settings.MEDIA_ROOT)

Django Movie_web/movie/home/models.py
from django.db import models

# Create your models here

class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Sub_Category(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE,null=False,default="")
    sub_category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE,null=False,default="")
    image = models.ImageField(null=True,blank=True)
    name = models.CharField(max_length= 200)
    price = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name



# class user(models.Model):
#     Name = models.CharField(max_length=200)
#     Username = models.CharField(max_length=200)
#     Email =models.EmailField(max_length=200)
#     Phone = models.CharField(max_length=13)
#     Password = models.CharField(max_length=30)
#
#     def __str__(self):
#         return self.Name
#
#     def isExists(self):
#         if user.objects.filter(Email = self.Email):
#             return True
#         return False
#     @staticmethod
#     def get_user_by_email(email):
#         try:
#             return user.objects.get(Email=email)
#         except:
#             return False

Django Movie_web/movie/home/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    password2 = forms.CharField(label="Confirm Passwort",widget=forms.PasswordInput)
    class Meta:
        model = User
        fields=["username","first_name","last_name","email",]

Django Movie_web/movie/home/views.py
from django.contrib.auth.hashers import check_password
from .models import *
from django.contrib import auth
from django.contrib.auth import authenticate,login
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render,redirect
from .forms import SignUpForm

# Create your views here.
def index(request):
    category1 = Category.objects.all()
    categoryID = request.GET.get("category")
    if categoryID:
        product1 = Product.objects.filter(sub_category = categoryID)
    else:
        product1 = Product.objects.all()
    context = {
        "category2":category1,
        "product2":product1
    }
    print(request.session.get("user_username"))
    return render(request,"store/index.html",context)


#signup
def signup(request):
    if request.method =="POST":
        fm = SignUpForm(request.POST)
        if fm.is_valid():
            fm.save()
    else:
        fm = SignUpForm()
    return render(request,"store/signup.html",{"form":fm})

#Login
def signin(request):
    if request.method =="POST":
        fm = AuthenticationForm(request = request,data=request.POST)
        if fm.is_valid():
            uname = fm.cleaned_data["username"]
            upass = fm.cleaned_data["password"]
            userO = authenticate(username = uname,password = upass)
            if userO is not None:
                request.session["user_username"] = userO.uname
                request.sessino["user_email"] = userO.email
                login(request,userO)
                return redirect("/")
    else:
        fm =AuthenticationForm()
    return render(request,"store/login.html",{"form":fm})

def logout(request):
    auth.logout(request)
    return redirect("/")

Django Movie_web/movie/templates/store/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %}
      {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">MOVIE</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Learn</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>
        {% for i in category2 %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
             data-bs-toggle="dropdown" aria-expanded="false">
            {{i.name}}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for j in i.sub_category_set.all %}
            <li><a class="dropdown-item" href="/?category={{j.id}}">{{j.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% endfor %}
      </ul>
      </div>
      <div class="buttons">
            <a type="button" class="btn btn-outline-success" href="#">
              Checkout
            </a>
            <a type="button" class="btn btn-outline-warning" href="#">
              Cart
            </a>
          </div>

      <div class="buttons">
        {% if user.is_authenticated  %}
            <a type="button" class="btn btn-outline-info" href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a type="button" class="btn btn-outline-info" href="{% url 'signin' %}">Sign in</a>
        {% endif %}
          </div>





   </div>

</nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


  {% block content %}

{% endblock content %}

<footer class="row row-cols-5 py-5 my-5 border-top">
    <div class="col">
      <a href="/" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#"></use></svg>
      </a>
      <h5 class="text-muted">
        movie
      </h5>
    </div>

    <div class="col">

    </div>

    <div class="col">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
      </ul>
    </div>

    <div class="col">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
      </ul>
    </div>

    <div class="col">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
      </ul>
    </div>
  </footer>


    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>

Django Movie_web/movie/templates/store/index.html
{% extends "./base.html" %}

{% load static %}

{% block title %} Home  {% endblock %}

{% block content %}
<div class="container-fluid my-4">

<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" >
      <img src="/static/image/aaa.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="/static/image/ss.jpg" class="d-block w-100"  alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="/static/image/hollywood.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>



<div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for j in product2 %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{j.image.url}}" class="d-block w-100" alt="..." height="500px;" >

            <div class="card-body" >
              <p class="card-text"><strong>{{j.name}}</strong></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <form action="/" method="POST">
                    {% csrf_token %}
                  <input type="submit"   class="btn btn-outline-warning" value="Add to Cart"></input>
                  </form>
                  <a class="btn btn-outline-success " href="#">View</a>
                </div>
                <h4 style="display:inline-block; float:right">{{j.price}} </h4>
              </div>
            </div>
          </div>
        </div>
{% endfor %}
      </div>
    </div>
  </div>



{% endblock content %}

Django Movie_web/movie/templates/store/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Sign in</title>
  </head>
  <body>
  <div class="container">
    <div class="p-4 m-4">
      <div class="col-lg-5 mx-auto">
        <div class="mx-auto m-4">
          <h1>Sign in</h1>
        </div>
          <form action="" method="post" style="max-width:440px; margin:auto;" novalidate>
            {% csrf_token %}
       {% for i in form %}
        {{i.label_tag}}  {{i}}  {{i.errors|striptags}} <br>
        <br>
          {% endfor %}

          <div class="mt-2">
      <button class="btn btn-outline-success" type="submit">Sign in</button>
  <a type="button" class="btn btn-outline-info" href="{% url 'signup' %}">Sign up</a>
</div>
  </form>


      </div>
    </div>

  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>

Django Movie_web/movie/templates/store/signup.html
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>Sign up</title>
</head>

<body>
  <div class="container">
    <div class="p-4 m-4">
      <div class="col-lg-5 mx-auto">
        <div class="mx-auto">
          <h1>Sign up</h1>
        </div>
        <form action="" method="post">
          {% csrf_token %}
          {% for i in form %}

          {{i.label_tag}}  {{i}}  {{i.errors|striptags}}<br> <br>

          {% endfor  %}
          <div class="mt-4">
      <button class="btn btn-outline-success" type="submit">Sign up</button>
  <a type="button" class="btn btn-outline-info" href="{% url 'signin' %}">Sign in</a>
</div>

        </form>
      </div>
    </div>

  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous">
  </script>
</body>

</html>